---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-studio
  labels:
    app: stable-studio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stable-studio
  template:
    metadata:
      labels:
        app: stable-studio
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/stable-studio/stable-studio:latest
          imagePullPolicy: Always
          name: container
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
      restartPolicy: Always
      serviceAccountName: stable-studio
      securityContext:
        runAsUser: 1001
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  name: stable-studio
  labels:
    app: stable-studio
spec:
  selector:
    app: stable-studio
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stable-studio
  labels:
    app: stable-studio


---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: stable-studio-ui
  labels:
    app: stable-studio
spec:
  to:
    kind: Service
    name: stable-studio
  tls:
    termination: edge
  port:
    targetPort: 3000
