FROM registry.redhat.io/ubi9/nodejs-16:1-138


USER 0
WORKDIR /app
COPY . .
RUN npm install --global yarn
RUN yarn install
RUN chown -R 1001:0 /app
RUN chown -R 1001:0 /opt/app-root

RUN fix-permissions /app -P
RUN fix-permissions /opt/app-root -P

USER 1001

EXPOSE 8080


CMD ["yarn", "dev"]
